# Inspecting tensors

The details of the various variables and methods for inspection of a tensor is available at https://www.tensorflow.org/api_docs/python/state_ops/

We will discuss a few variables below. The graph to which a given tensor belongs can be obtained using graph variable. 

The 'op' variable returns the details of the operations in a given tensor. For example in the mainno variable, the op returns the fact that the operation is random_uniform, the output type is int32 and the seed (3457) obtained from the graph.

A call to 'op' variable for powerballno shows that the operation is concatenate and that there are two calls to random_uniform function.

In [6]:
import tensorflow as tf
tf.set_random_seed(3457)
mainno = tf.random_uniform(shape=(5, ), minval=1, maxval=59, dtype=tf.int32)
lastno = tf.random_uniform((1, ), minval=1, maxval=35, dtype=tf.int32)
powerballno = tf.concat([mainno, lastno, mainno], 0)
with tf.Session() as sess1:
    print(sess1.run(powerballno))

with tf.Session() as sess2:
    print(sess2.run(powerballno))
    
# Properties of a variable 
print("-------- Graph Object --------")
print(powerballno.graph)

#print("-------- Operations in mainno --------")
#print(mainno.op)

#print("-------- Operations in powerballno --------")
print(powerballno.op)

[45 24 43 22 14 12 45 24 43 22 14]
[45 24 43 22 14 12 45 24 43 22 14]
-------- Graph Object --------
name: "concat_5"
op: "ConcatV2"
input: "random_uniform_10"
input: "random_uniform_11"
input: "random_uniform_10"
input: "concat_5/axis"
attr {
  key: "N"
  value {
    i: 3
  }
}
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}



To get a list of all the properties and variables associated with a given variable, use the dir() function.

In [2]:
print(dir(mainno))

['OVERLOADABLE_OPERATORS', '__abs__', '__add__', '__and__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__invert__', '__iter__', '__le__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_add_consumer', '_as_node_def_input', '_as_tf_output', '_consumers', '_dtype', '_handle_dtype', '_handle_shape', '_op', '_override_operator', '_shape', '_shape_as_list', '_value_index', 'consumers', 'device', 'dtype', 

As can be seen in the example above, the variable mainno has many "magic" methods, the methods that have \_\_ (double underscore a.k.a dunder) on either sides. You can find more details about magic methods at https://docs.python.org/3/reference/datamodel.html#special-method-names.  We will demonstrate the use of magic methods using an example.

We will create 2 variables var1 and var2 using numpy and convert them to tensors using tf.constant. The variable var1 is of size (1, 3,) and all its values are equal to 5. The variable var2 is also of size (1, 3,) and all its values are equal to 1. The variables are added using three methods, one using a magic method and the second using add function and the third using the operator +. The operations  stored in to variables sumvar_dunder, sumvar_nondunder and sumvar_operator. When a session is started and executed, the three methods yield the same value, a tensor of length 3 containing values of 6. 



It is important to note the following:
1. The three mechanisms produce the same result.
2. The use of + operator is 'pythonic' while the use of add or \_\_add\_\_ is not.
3. The use of + operator produces a readable code while the use of add or \_\_add\_\_ does not.
4. The + operator overloads the meaning of addition of tensors using \_\_add\_\_ method.

In [3]:
import numpy as np

var1 = tf.constant(np.ones((1, 3,))*5)
var2 = tf.constant(np.ones((1, 3,)))

sumvar_dunder = var1.__add__(var2)
print(sumvar_dunder, sumvar_dunder.name)

sumvar_nondunder = tf.add(var1, var2)
print(sumvar_nondunder, sumvar_nondunder.name)

sumvar_operator = var1 + var2
print(sumvar_operator, sumvar_operator.name)

with tf.Session() as sess1:
    print(sess1.run(sumvar_dunder))
    print(sess1.run(sumvar_nondunder))
    print(sess1.run(sumvar_operator)) 

Tensor("add:0", shape=(1, 3), dtype=float64) add:0
Tensor("Add:0", shape=(1, 3), dtype=float64) Add:0
Tensor("add_1:0", shape=(1, 3), dtype=float64) add_1:0
[[ 6.  6.  6.]]
[[ 6.  6.  6.]]
[[ 6.  6.  6.]]


In [5]:
print(tf.get_default_graph().get_operations())

[<tf.Operation 'random_uniform/shape' type=Const>, <tf.Operation 'random_uniform/min' type=Const>, <tf.Operation 'random_uniform/max' type=Const>, <tf.Operation 'random_uniform' type=RandomUniformInt>, <tf.Operation 'random_uniform_1/shape' type=Const>, <tf.Operation 'random_uniform_1/min' type=Const>, <tf.Operation 'random_uniform_1/max' type=Const>, <tf.Operation 'random_uniform_1' type=RandomUniformInt>, <tf.Operation 'random_uniform_2/shape' type=Const>, <tf.Operation 'random_uniform_2/min' type=Const>, <tf.Operation 'random_uniform_2/max' type=Const>, <tf.Operation 'random_uniform_2' type=RandomUniformInt>, <tf.Operation 'random_uniform_3/shape' type=Const>, <tf.Operation 'random_uniform_3/min' type=Const>, <tf.Operation 'random_uniform_3/max' type=Const>, <tf.Operation 'random_uniform_3' type=RandomUniformInt>, <tf.Operation 'concat_1/axis' type=Const>, <tf.Operation 'concat_1' type=ConcatV2>, <tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation '

In [6]:
W = tf.Variable(tf.random_uniform((784, 100), -1, 1))
x = tf.placeholder(tf.float32, (100, 784))
h = tf.nn.relu(tf.matmul(x, W))
print(tf.get_default_graph().get_operations())

[<tf.Operation 'random_uniform/shape' type=Const>, <tf.Operation 'random_uniform/min' type=Const>, <tf.Operation 'random_uniform/max' type=Const>, <tf.Operation 'random_uniform' type=RandomUniformInt>, <tf.Operation 'random_uniform_1/shape' type=Const>, <tf.Operation 'random_uniform_1/min' type=Const>, <tf.Operation 'random_uniform_1/max' type=Const>, <tf.Operation 'random_uniform_1' type=RandomUniformInt>, <tf.Operation 'random_uniform_2/shape' type=Const>, <tf.Operation 'random_uniform_2/min' type=Const>, <tf.Operation 'random_uniform_2/max' type=Const>, <tf.Operation 'random_uniform_2' type=RandomUniformInt>, <tf.Operation 'random_uniform_3/shape' type=Const>, <tf.Operation 'random_uniform_3/min' type=Const>, <tf.Operation 'random_uniform_3/max' type=Const>, <tf.Operation 'random_uniform_3' type=RandomUniformInt>, <tf.Operation 'concat_1/axis' type=Const>, <tf.Operation 'concat_1' type=ConcatV2>, <tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation '

In [7]:
# A feed in tensorflow is a dictionary that maps the nodes in the 
# graph to concrete values.
print(dir(tf.get_variable_scope()))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_caching_device', '_custom_getter', '_dtype', '_get_partitioned_variable', '_initializer', '_name', '_name_scope', '_partitioner', '_regularizer', '_reuse', 'caching_device', 'custom_getter', 'dtype', 'get_variable', 'initializer', 'name', 'original_name_scope', 'partitioner', 'regularizer', 'reuse', 'reuse_variables', 'set_caching_device', 'set_custom_getter', 'set_dtype', 'set_initializer', 'set_partitioner', 'set_regularizer']
