In [22]:
import tensorflow as tf
import numpy as np

## 10_data types

In [1]:
'''
In-class activity: Create a tensor, A with constant() with value -11. Create another tensor, B  with 
value 9. Add the tensors, and call it C. Then run C and print the output. 
'''
A = tf.constant(-11)
B = tf.constant(9)
C = A + B
with tf.Session() as sess:
    print(sess.run(C))

-2


In [5]:
'''
In-class activity: Create a tensor, D with constant() with values [7, 8, 10]. Create another tensor, 
E of size (1, 3) using fill() that has value 10. Add the tensors, and call it F.
Then run F and print the output. 
'''
D = tf.constant([7, 8, 10])
E = tf.fill((1,3), 10)
F = D + E
with tf.Session() as sess:
    print(sess.run(F))

[[17 18 20]]


In [8]:
'''
In-class activity: Create a placeholder tensor, W1 of shape (2, 2). Create a numpy array I with 
values [1, 0], [0, 1]. Define another tensor M that computes I*I. Run M and feed I.
'''
I = np.array([[1, 0],[0, 1]])
w1 = tf.placeholder(tf.float32, shape=(2,2))
M = tf.matmul(I, I)
with tf.Session() as sess:
    print(sess.run(M, feed_dict={w1: I}))

[[1 0]
 [0 1]]


In [15]:
'''
In-class activity: Create a tensor, v1 using Variable() with values [2, 4, 6]. 
Create another tensor, v2 using Variable() with values [4 6 8]. Define v3 as the sum of v1 and v2. 
initialize the variable values and then run and print v3.
'''
v1 = tf.Variable(tf.constant([2, 4, 6], name = 'variable1'))
v2 = tf.Variable(tf.constant([4, 6, 8], name="variable2"))

v3 = tf.subtract(v1, v2)
init_all_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_all_op)
    print(sess.run(v3))

[-2 -2 -2]


## 20_transformations

In [17]:
'''
In-class activity: Define a tensor, T1 with values [31, 37, 41] then print the dtype of this tensor. 
Then change T1's dtype to float using 
1) to_float()
2) cast()
'''
T1 = tf.constant([31, 37, 41])
print(T1)
T11 = tf.cast(T1, tf.float32)  # Cast the individual elements from int32 to float32
print("T11:", T11)
T12 = tf.to_float(T1)  # Specialized function. 
print("T12:", T12)

Tensor("Const_7:0", shape=(3,), dtype=int32)
T11: Tensor("Cast:0", shape=(3,), dtype=float32)
T12: Tensor("ToFloat_1:0", shape=(3,), dtype=float32)


In [ ]:
'''
In-class activity: Create a tensor with shape (12, 1, 14) and then drop the dimension 1.
'''
t1 = tf.zeros((12, 1, 14))
t2 = tf.squeeze(t1) # squeeze removes dimensions of size 1
print(t1)
print(t2)

In [18]:
'''
In-class activity: If T1 = [[12, 13, 11], [9, 11, 9], [2, 5, 7]]. How can we slice T1 so that we 
get tensor with values [9, 11, 9].
'''
T1 = tf.constant([[12, 13, 11], [9, 11, 9], [2, 5, 7]])
T2 = tf.slice(T1, [1,0], [1, 3])
with tf.Session() as sess1:
    print(sess1.run(T1))
    print(sess1.run(T2))

[[12 13 11]
 [ 9 11  9]
 [ 2  5  7]]
[[ 9 11  9]]


## 30_mathematical_operations

In [29]:
'''
In-class activity: Create a tensor, T1 = [[384,396,408], [180,192,204]] and T2 = [[4, 3, 12], [2, 6, 12]]
Find the following:
1) divide T1 with T2
2) find cumsum of T1, T2 and T2
'''
T1 = tf.constant([[384,396,408], [180,192,204]])
T2 = tf.constant([[4, 3, 12], [2, 6, 12]])

#1 divide T1 with T2
Tdiv = tf.truediv(T1, T2)

#2 find cumsum of T1, T2 and T2
Tcumsum = tf.cumsum([T1, T2, T2])

with tf.Session() as sess:
    print(sess.run(Tdiv))
    print(sess.run(Tcumsum))


[[  96.  132.   34.]
 [  90.   32.   17.]]
[[[384 396 408]
  [180 192 204]]

 [[388 399 420]
  [182 198 216]]

 [[392 402 432]
  [184 204 228]]]


## 40_simple_examples

In [25]:
'''
In-class activity: If T = [[121, 99, 145], [45, 119, 225], [235, 170, 723]]
Find
1) the minimum value in T and print it
2) the maximum value in T and print it
'''
T = tf.constant([[121, 99, 145], [45, 119, 225], [235, 170, 723]])
min1 = tf.reduce_min(T)
max1 = tf.reduce_max(T)
with tf.Session() as sess:
    print(sess.run(min1))
    print(sess.run(max1))

45
723


In [27]:
'''
In-class activity: If T = [[121, 99, 145], [45, 119, 0], [235, 170, 723]]. Let eps = 0.001. 
Find
1) add eps to every element in T
2) compute the log of the tensor that is obtained in 1).
'''
T = tf.constant([[121, 99, 145], [45, 119, 0], [235, 170, 723]], tf.float32)
eps = tf.constant(0.001)
Teps = T+eps
Tlog = tf.log(Teps)
with tf.Session() as sess:
    print(sess.run(Tlog))

[[ 4.79579878  4.59512997  4.97674084]
 [ 3.80668473  4.77913189 -6.90775537]
 [ 5.45958996  5.13580418  6.58341074]]


In [ ]:

'''
In-class activity

1. Apply log transformation to the placeholder image, img. Make sure to add eps to it, so that we do not calculate log(0)

2. Calculate the maximum value in the tensor from the previous step across all dimensions

3. Calculate the minimum value in the tensor from the previous step across all dimensions

4. Scale the tensor, so that the resultant tensor can only have values from 0 to 255. Use the 
formula maxpixelvalue*(logval-min)/(max-min)
'''

import cv2
import tensorflow as tf

logoimg = cv2.imread('tensorflow_logo_gray.png',0)
print(logoimg.shape)

maxpixelvalue = tf.constant(255, dtype=tf.float32)
img = tf.placeholder(tf.float32, shape=None)
eps = tf.constant(1e-5, dtype=tf.float32)

logtransformed = tf.log(img+eps)
maxval = tf.reduce_max(logtransformed)
minval = tf.reduce_min(logtransformed)
scaledlogtransformed = maxpixelvalue*(logtransformed-minval)/(maxval-minval)
print(scaledlogtransformed)

with tf.Session() as sess1:
    scaledimg = sess1.run(scaledlogtransformed, feed_dict={img: logoimg})
    
cv2.imwrite('logoimage.png', scaledimg)

## 90_CNN_LeNet

In [ ]:
'''
In-class activity:
1. Add one more layer after conv2. The new layer will also have kernel of size 5 x 5, 128 of them.
2. The resultant output of the filter will be a 4*4 image.
3. Add bias as well with a length of 128. 
4. Rerun the architecture.
'''
# The solution to this is provided in 91_CNN_LeNet_modified.ipynb